package view;

import javax.swing.JOptionPane;
import model.DaoPaises;
import model.Veiculo;

/**
 *
 * @author aluno.lab
 */
public class VeiculoView extends javax.swing.JFrame {
    
    Veiculo veiculo; 
    DaoPaises daoVeiculo;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VeiculoView.class.getName());

    /**
     * Creates new form VeiculoView
     */
    public VeiculoView() {
        daoVeiculo = new DaoPaises();
        initComponents();
        this.atualizarTabelaVeiculos();
        
    }
    
    public void atualizarTabelaVeiculos(){
        jTableVeiculo.setModel(new VeiculoTableModel(daoVeiculo.buscarTodos()));
    
    
    
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgFiltro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfCodigo1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfModelo = new javax.swing.JTextField();
        tfChassi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfAno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bt_Salvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        RbMarca = new javax.swing.JRadioButton();
        RbModelo = new javax.swing.JRadioButton();
        tfFiltro = new javax.swing.JTextField();
        BtFiltrar = new javax.swing.JButton();
        BtMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Veiculos");

        jLabel2.setText("Codigo:");

        tfMarca.addActionListener(this::tfMarcaActionPerformed);

        jLabel3.setText("Marca:");

        tfCodigo1.setEditable(false);
        tfCodigo1.addActionListener(this::tfCodigo1ActionPerformed);

        jLabel4.setText("Modelo:");

        tfChassi.addActionListener(this::tfChassiActionPerformed);

        jLabel5.setText("Ano:");

        tfAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAnoFocusLost(evt);
            }
        });

        jLabel6.setText("Chassi:");

        bt_Salvar.setText("Salvar");
        bt_Salvar.addActionListener(this::bt_SalvarActionPerformed);

        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVeiculo);

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(this::btExcluirActionPerformed);

        jLabel7.setText("Filtrar por: ");

        BgFiltro.add(RbMarca);
        RbMarca.setText("Marca");
        RbMarca.addActionListener(this::RbMarcaActionPerformed);

        BgFiltro.add(RbModelo);
        RbModelo.setText("Modelo");
        RbModelo.addActionListener(this::RbModeloActionPerformed);

        tfFiltro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFiltroFocusLost(evt);
            }
        });

        BtFiltrar.setText("Filtrar");
        BtFiltrar.addActionListener(this::BtFiltrarActionPerformed);

        BtMostrar.setText("Mostrar Todos");
        BtMostrar.addActionListener(this::BtMostrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfChassi, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(tfMarca))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfModelo)
                                    .addComponent(tfAno)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bt_Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RbModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtFiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtMostrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Salvar)
                    .addComponent(btExcluir))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(RbMarca)
                    .addComponent(RbModelo)
                    .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtFiltrar)
                    .addComponent(BtMostrar))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMarcaActionPerformed

    private void tfCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigo1ActionPerformed

    private void tfChassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChassiActionPerformed

    private void bt_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SalvarActionPerformed
        
        if(tfMarca.getText().equals("") || tfModelo.getText().equals("") || tfChassi.getText().equals("") || tfAno.getText().equals("")){ 
            
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "AVISO", JOptionPane.WARNING_MESSAGE);

        }else{
            veiculo = new Veiculo();
            veiculo.setMarca(tfMarca.getText());
            veiculo.setModelo(tfModelo.getText());
            veiculo.setChassi(tfChassi.getText());
            veiculo.setAno(Integer.parseInt(tfAno.getText()));
            
            if(tfCodigo1.getText().equals("")){
                daoVeiculo.inserir(veiculo);
            
            }else{
                veiculo.setCodigo(Integer.parseInt(tfCodigo1.getText()));
                daoVeiculo.alterar(veiculo);
            }
            
            limparCampos();
            atualizarTabelaVeiculos();
        }
    }//GEN-LAST:event_bt_SalvarActionPerformed
    
    //Tabela foi clicada
    private void jTableVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVeiculoMouseClicked
        tfCodigo1.setText(
                jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 
                    VeiculoTableModel.COL_CODIGO).toString()); 
        
        tfMarca.setText( jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), VeiculoTableModel.COL_MARCA).toString()); 
        tfModelo.setText( jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), VeiculoTableModel.COL_MODELO).toString()); 
        tfChassi.setText( jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), VeiculoTableModel.COL_CHASSI).toString()); 
        tfAno.setText( jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), VeiculoTableModel.COL_ANO).toString()); 
        
        btExcluir.setEnabled(true);
        
        
    }//GEN-LAST:event_jTableVeiculoMouseClicked

    private void tfAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAnoFocusLost
        if(!tfAno.getText().equals("")){
          try{
            int i = Integer.parseInt(tfAno.getText());
            
          }catch(NumberFormatException e){
              JOptionPane.showMessageDialog(null, "O ano deve ser um número inteiro" , "AVISO", JOptionPane.WARNING_MESSAGE);
              tfAno.setText("");
          }
        }
    }//GEN-LAST:event_tfAnoFocusLost

    private void RbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbMarcaActionPerformed

    private void RbModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbModeloActionPerformed

    private void tfFiltroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFiltroFocusLost
        
    }//GEN-LAST:event_tfFiltroFocusLost

    private void BtFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFiltrarActionPerformed
        String campo = "";
        if(RbMarca.isSelected()){
            campo = "marca";
            
        } else {
            campo = "modelo";
        }
        jTableVeiculo.setModel(new VeiculoTableModel (daoVeiculo.buscarTodosFiltro(campo, tfFiltro.getText())));
        limparCampos();
        
    }//GEN-LAST:event_BtFiltrarActionPerformed

    private void BtMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMostrarActionPerformed
        limparCampos();
        tfFiltro.setText("");
        atualizarTabelaVeiculos();
    }//GEN-LAST:event_BtMostrarActionPerformed
    
    //Tabela foi clicada
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt){
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do veiculo codigo " + tfCodigo1.getText() + "?", "Exclusão de Veiculo", JOptionPane.YES_NO_OPTION);

        if (confirma == 0){
            daoVeiculo.excluir(Integer.parseInt(tfCodigo1.getText()));
            limparCampos();
            atualizarTabelaVeiculos();
        }
    }
  
    
    public void limparCampos(){
    
        //tfCodigo.setText("");
        tfMarca.setText("");
        tfModelo.setText("");
        tfChassi.setText("");
        tfAno.setText("");
        btExcluir.setEnabled(false);
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VeiculoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BgFiltro;
    private javax.swing.JButton BtFiltrar;
    private javax.swing.JButton BtMostrar;
    private javax.swing.JRadioButton RbMarca;
    private javax.swing.JRadioButton RbModelo;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton bt_Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextField tfChassi;
    private javax.swing.JTextField tfCodigo1;
    private javax.swing.JTextField tfFiltro;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfModelo;
    // End of variables declaration//GEN-END:variables
}
